### ISSUE TITLE
Audio and video are out of sync with a VOD content in HLS format

### ISSUE THREAD

**Issue by FelipeAndresLopez** [shaka-project/shaka-player#5482]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.3.8

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome - MacOS

**What are the manifest and license server URIs?**
The HLS manifest was shared by email

**What did you do?**

1. Open the Shaka Player DEMO v4.3.8
2. Add the above manifest as a custom content
3. Play the VOD content
4. Advance the content until the 30 minute

**What did you expect to happen?**
Audio and video should keep synchronized

**What actually happened?**
Audio and video are not synchronized

**Comment by avelad** [comment]
@FelipeAndresLopez  can you try with the main branch? Yesterday I fixed some AV sync issues.

**Comment by FelipeAndresLopez** [comment]
> @FelipeAndresLopez can you try with the main branch? Yesterday I fixed some AV sync issues.

Hi @avelad, first of all, thanks for answering and checking this issue.
can this bug fix be testable with the Shaka Player Demo v4.4.2? If yes, the issue persists and I can send you the manifest in HLS that we are using. If not, let me know how I can test it.

**Comment by avelad** [comment]
You can use: https://nightly-dot-shaka-player-demo.appspot.com/demo/

**Comment by FelipeAndresLopez** [comment]
I just tested and the result is this:
When playback starts goes well, and as long as nothing changes, it continues working normally. 
However when I change the language to Spanish (for instance) or I fast-forward the movie, the audio and video synchronization issue starts appearing.
Let me know if you need the HLS file that I'm testing for better debugging. I could send you by email.

**Comment by cristian-atehortua** [comment]
Looks like this issue is being mitigated by new configs. Setting `manifest.hls.sequenceMode` to `false` and `manifest.hls. ignoreManifestTimestampsInSegmentsMode` to `true`.

**Comment by cristian-atehortua** [comment]
@avelad in those streams, it is also fixed with the settings in the previous comment?

> Looks like this issue is being mitigated by new configs. Setting `manifest.hls.sequenceMode` to `false` and `manifest.hls.ignoreManifestTimestampsInSegmentsMode` to `true` the video and audio are in sync.

**Comment by avelad** [comment]
Yes with that settings the problem disappears, but we need fix the default setting

**Comment by avelad** [comment]
@FelipeAndresLopez Can you send the manifest url to shaka-player-maintainers@googlegroups.com ? Thanks!

**Comment by avelad** [comment]
> @avelad we also have some streams where this issue occurs. The HLS manifests are only valid for an hour, but you can always get a fresh manifest by doing this:
> 
>     * open https://www.buzzfeed.de/meinung/verbale-sexuelle-belaestigung-spd-gesetzesvorschlag-gesetz-catcalling-kommentar-video-92353864.html?info
> 
>     * mouse over the video-player
> 
>     * check the network tab for the `stream.m3u8` file
> 
> 
> When the stream gets seeked to the end, the issue becomes noticeable.

Your stream is wrong, audio and video playlist duration is different 101 vs 105 (adding all EXTINF values), that causes the player to be out of sync, fix that and the player will work properly. Thanks!

**Comment by avelad** [comment]
@robwalch How does hls.js work in the event that the PDT between updates is bad? (see my previous comment)

**Comment by avelad** [comment]
Shaka is appending media according to playlist durations and not media timestamps so drift in the playlist is not corrected. You have to talk to your provider to correct this. This is the way Shaka works, sorry!

**Comment by cristian-atehortua** [comment]
@shaka-bot reopen

This issue was opened before new discussion this months.

@avelad said that he replicated the issue.

It should keep opened until fixed.

Just to recap, there's a workaround: 

Setting `manifest.hls.sequenceMode` to `false` and setting `manifest.hls.ignoreManifestTimestampsInSegmenstMode` to `true`

@avelad commented that it should work without those configs

**Comment by cristian-atehortua** [comment]
@shaka-bot reopen

**Comment by avelad** [comment]
@cristian-atehortua Just because it works by chance with some configuration (some errors are displayed in the console) does not mean that the stream is correct.

![imagen](https://github.com/shaka-project/shaka-player/assets/8983024/3c35e4a9-6bf3-4c11-9b0b-41a253365eb8)

**Comment by avelad** [comment]
I attach the mediaStreamValidator report:

[validation_data.html.zip](https://github.com/user-attachments/files/16178975/validation_data.html.zip)

I attach the two main problems reported by the Apple tool:

![imagen](https://github.com/shaka-project/shaka-player/assets/8983024/cd99de37-ca41-4f9e-a69a-69eaebb2b8bc)

**Comment by cristian-atehortua** [comment]
> I have reproduced the same error with the streams from https://github.com/shaka-project/shaka-player/issues/5445

**Comment by avelad** [comment]
> [#5445 (comment)](https://github.com/shaka-project/shaka-player/issues/5445#issuecomment-1841050557)

If someone wants to provide a stream, I can look at it again, but the only functional stream for this issue has those problems.

**Comment by jspizziri** [comment]
@avelad I have a stream that's falling out of sync when the bitrate changes. I've attempted to validate the stream but I can't find the same `mediastreamvalidator` you referenced above. I downloaded a tool from apple but its not generating the same reporting as you sent along.

I'd be happy to privately send you an HLS stream for testing.

**Comment by jspizziri** [comment]
FWIW, I'm using `shaka-streamer`/`shaka-packager` which, in turn is using `ffmpeg`. One of the things I noticed about my HLS manifest files is that the length of the audio segments is ever so slightly different from the length of the video segments.
