### ISSUE TITLE
AV sync regression for HLS live for 2 seconds AV separated content

### ISSUE THREAD

**Issue by shashikantkonded-git** [shaka-project/shaka-player#5528]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Chromecast ShakaPlayer

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome

**What are the manifest and license server URIs?**
Will send it in separate email.

**What did you do?**
We have tried playing the HLS LIVE content with 3.3.19, the content is playing fine without AV sync issues. From 4.x any versions and even with latest exhibiting the AV sync issue.
Our contents are 2 seconds AV separated.

**What did you expect to happen?**
The content should play without AV sync issues.

**What actually happened?**
We have checked the other related issues in the project. All are distinct in use case or in contents. We don't have ads in our project. We have tried,
https://v3-3-19-dot-shaka-player-demo.appspot.com/    ->    no issue
https://nightly-dot-shaka-player-demo.appspot.com/      ->    issue exists

**Comment by joeyparrish** [comment]
The big difference between v3.3 and v4.0 for HLS is the use of MediaSource sequence mode.  For content without necessary time-sync tags (EXT-X-PROGRAM-DATE-TIME), disabling sequence mode may fix sync issues.

Shaka Player v4.4.0 adds a flag to control the use of sequence mode: `manifest.hls.sequenceMode`: `false`

Does this help?

**Comment by shashikantkonded-git** [comment]
@joeyparrish We're running version 4.3.6, and the sequenceMode setting is set to off by default. We're using Shaka Player in Chromecast SDK and can't upgrade to 4.4 since Google Chromecast SDK requires support.
But I tried the mentioned parameters in the [v4.4.0](https://shaka-player-demo.appspot.com/demo/#build=uncompiled) online demo player. The av sync problem continues to be present.

**Comment by shashikantkonded-git** [comment]
I have sent the content link through email. Can you please check once?

**Comment by avelad** [comment]
@joeyparrish can you review it?

**Comment by avelad** [comment]
@shashikantkonded-git can you try with the main branch? Yesterday I fixed some AV sync issues.

**Comment by shashikantkonded-git** [comment]
I have tested the streams with [nightly](https://nightly-dot-shaka-player-demo.appspot.com/demo/#build=uncompiled) build. The 2 sec issue still persists.

**Comment by avelad** [comment]
@shashikantkonded-git  Can you try if `manifest.hls.sequenceMode = false` config fixes your issue? Thanks!

**Comment by shashikantkonded-git** [comment]
We tested all possible combinations of "Ignore Program Date Time", "Enable HLS sequence mode", and "Ignore Manifest Timestamps in Segments Mode".
We can still see the AV sync issue on latest nightly build.

**Comment by shashikant-xgit** [comment]
@avelad We are still experiencing a two-second delay with the most recent (4.7.6) version. I see the milestone is updated to 5.0. Is there a timeline for the 5.0 release?

**Comment by avelad** [comment]
The version has been updated, because we have closed the old one, but right now there is no one working on this issue and I don't think it will available version 5.0.

**Comment by shashikant-xgit** [comment]
@avelad The content URL is sent to the above email ID.

**Comment by avelad** [comment]
@shashikant-xgit I have responded to your email telling you where the error is in your stream. The stream has a wrong baseMediaDecodeTime and that is why in Shaka you see the difference of approximately 2 seconds. Thanks!

**Comment by avelad** [comment]
In reality, just because Shaka 3.x does things wrong and tolerates streams that are wrong doesn't mean that 4.x has to do it. I can try to explore some quick solution, but I don't think it is the right solution.

**Comment by avelad** [comment]
@shashikant-xgit Can you change EXT-X-PROGRAM-DATE-TIME on your manifest? Can you account for 1.8 seconds of driff in the EXT-X-PROGRAM-DATE-TIME in the audio playlist?

**Comment by shashikant-xgit** [comment]
@avelad Yes, we did adjust the EXT-X-PROGRAM-DATE-TIME values by 1.8 seconds in the manifest, and it worked fine. We are using Chromecast Shaka-Player, and we don't have the luxury of using a custom player.
The introduction of any Shaka-Player configuration would help us instead.

**Comment by avelad** [comment]
@shashikant-xgit I have a fix for it, but until next week there will not be a release with the fix.

**Comment by shashikant-xgit** [comment]
@avelad That's great news! We will wait for the release.
Thanks for the fix.
