### ISSUE TITLE
Request to release new shaka players (4.7.3) for Chromecast

### ISSUE THREAD

**Issue by wjywbs** [shaka-project/shaka-player#6074]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
On https://developers.google.com/speed/libraries#shaka-player, the shaka player versions available to use on Chromecast are 4.7.0, 4.6.4, etc.

**Describe the solution you'd like**
Could you help to release the new shaka player versions since 4.7.0 to ajax.googleapis.com? I hope to use shaka player 4.7.3 that includes a bug fix in a custom Chromecast receiver.

**Describe alternatives you've considered**
Is there some process to automatically release new shaka players to Chromecast?

**Additional context**

**Comment by avelad** [comment]
@theodab is working on it!

**Comment by theodab** [comment]
There was a bug in the process that pushed versions to the hosted libraries, but it's been fixed now, and now we have up to v4.7.5 there.

**Comment by wjywbs** [comment]
Hello @theodab, thanks for the update. Although this page has been updated https://developers.google.com/speed/libraries#shaka-player, accessing the js file still shows 404:

https://ajax.googleapis.com/ajax/libs/shaka-player/4.7.5/shaka-player.compiled.js

@shaka-bot reopen

**Comment by theodab** [comment]
It's up now. I think it just takes a few hours for it to be automatically copied from our internal repository to the public site? Sorry for the confusion.
