### ISSUE TITLE
DASH Content Not Playing on Chromecast Despite Successful Connection

### ISSUE THREAD

**Issue by DevKeytech** [shaka-project/shaka-player#8447]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not applicable (this is a Chromecast issue)

**What version of Shaka Player are you using?**

Latest CDN version ( //cdn.jsdelivr.net/npm/shaka-player@latest/dist/shaka-player.ui.min.js )

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both. I can reproduce the issue in both my custom application and on the official Shaka Player demo page.

**If custom app, can you reproduce the issue using our demo app?**
Yes, the issue also occurs on the official demo app at https://shaka-player-demo.appspot.com/demo when trying to cast DASH content.

**What browser and OS are you using?**
Chrome on Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Google TV Chromecast

**What are the manifest and license server URIs?**

I'm using DASH DRM content with ClearKey

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

{
  "drm": {
    "clearKeys": {
      "xxxx": "xxxx"
    }
  }
}

UI Config:
{
  "addSeekBar": false,
  "customContextMenu": true,
  "controlPanelElements": [
    "play_pause", "spacer", "mute", "volume", "fullscreen", 
    "quality", "overflow_menu", "airplay"
  ],
  "overflowMenuButtons": ["cast", "picture_in_picture"]
}

Chromecast configuration attributes in HTML:
data-shaka-player-cast-receiver-id="07AEE832" 
data-shaka-player-cast-android-receiver-compatible="true"

**What did you do?**

Loaded my Shaka Player page with DASH content and Clear Key DRM
Clicked the Cast button to stream to my Chromecast device
The Chromecast icon indicates connection was successful
However, the video does not start playing on the TV

I also tried the same steps on the official Shaka Player demo with their DASH live stream content, and encountered the same issue.

**What did you expect to happen?**
The video should start playing on the Chromecast device after selecting it from the Cast menu.

**What actually happened?**

When casting to the Chromecast, the connection appears successful (the icon changes to indicate connection), but the video does not start playing on the TV screen. The event listener for 'caststatuschanged' shows the connection is established, but playback does not begin.

I've verified that:

The Chromecast is properly connected to the network
Other casting applications work correctly
The same problem occurs with both my custom implementation and on the official Shaka Player demo site

**Are you planning to send a PR to fix it?**
No, I'm reporting the issue for the Shaka Player team to investigate.

**Important regression information** 
This functionality was working correctly until a few days ago with the exact same code and configuration. I've tried downgrading to previous versions of Shaka Player, but the issue persists, suggesting it might be related to a change in the Chromecast receiver app.

**Comment by avelad** [comment]
I tested with https://nightly-dot-shaka-player-demo.appspot.com/demo/ (main branch) and there is no issue...

**Comment by DevKeytech** [comment]
This doesn't always work. You can test it with this link: <a href="https://shaka-player-demo.appspot.com/demo/#audiolang=it-IT;textlang=it-IT;uilang=it-IT;assetBase64=eyJuYW1lIjoiQmlnIEJ1Y2sgQnVubnk6IHRoZSBEYXJrIFRydXRocyBvZiBhIFZpZGVvIERldiBDYXJ0b29uIChITFMpIiwic2hvcnROYW1lIjoiQmlnIEJ1Y2sgQnVubnk6IHRoZSBEYXJrIFRydXRocyIsImljb25VcmkiOiJodHRwczovL3N0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vc2hha2EtYXNzZXQtaWNvbnMvZGFya190cnV0aC5wbmciLCJtYW5pZmVzdFVyaSI6Imh0dHBzOi8vc3RvcmFnZS5nb29nbGVhcGlzLmNvbS9zaGFrYS1kZW1vLWFzc2V0cy9iYmItZGFyay10cnV0aHMtaGxzL2hscy5tM3U4Iiwic291cmNlIjoiU2hha2EiLCJmb2N1cyI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwiZXh0cmFUZXh0IjpbXSwiZXh0cmFUaHVtYm5haWwiOltdLCJleHRyYUNoYXB0ZXIiOltdLCJjZXJ0aWZpY2F0ZVVyaSI6bnVsbCwiZGVzY3JpcHRpb24iOiJBIHNlcmlvdXMgZG9jdW1lbnRhcnkgYWJvdXQgYSBwcm9ibGVtIHBsYWd1aW5nIHZpZGVvIGRldmVsb3BlcnMuIiwiaXNGZWF0dXJlZCI6dHJ1ZSwiZHJtIjpbIk5vIERSTSBwcm90ZWN0aW9uIl0sImZlYXR1cmVzIjpbIkRvd25sb2FkYWJsZSIsIkhpZ2ggZGVmaW5pdGlvbiIsIkhMUyIsIk1QNCIsIlZPRCJdLCJsaWNlbnNlU2VydmVycyI6eyJfX3R5cGVfXyI6Im1hcCJ9LCJvZmZsaW5lTGljZW5zZVNlcnZlcnMiOnsiX190eXBlX18iOiJtYXAifSwibGljZW5zZVJlcXVlc3RIZWFkZXJzIjp7Il9fdHlwZV9fIjoibWFwIn0sInJlcXVlc3RGaWx0ZXIiOm51bGwsInJlc3BvbnNlRmlsdGVyIjpudWxsLCJjbGVhcktleXMiOnsiX190eXBlX18iOiJtYXAifSwiZXh0cmFDb25maWciOm51bGwsImV4dHJhVWlDb25maWciOm51bGwsImFkVGFnVXJpIjpudWxsLCJpbWFWaWRlb0lkIjpudWxsLCJpbWFBc3NldEtleSI6bnVsbCwiaW1hQ29udGVudFNyY0lkIjpudWxsLCJpbWFNYW5pZmVzdFR5cGUiOm51bGwsIm1lZGlhVGFpbG9yVXJsIjpudWxsLCJtZWRpYVRhaWxvckFkc1BhcmFtcyI6bnVsbCwidXNlSU1BIjp0cnVlLCJtaW1lVHlwZSI6bnVsbH0=;panel=HOME;build=uncompiled">Shaka Player Demo</a>.

If you try to cast the video to Chromecast from there, it still doesn't work. The video fails to cast.

![Image](https://github.com/user-attachments/assets/ae47a738-c2c9-4135-b296-0e5d5e70d3ef)

However, if I restart the video playback using the play button on one of the 5 cards below the player (not the main UI play button), the video does start casting to Chromecast.

**Comment by avelad** [comment]
I fixed that this morning --> https://github.com/shaka-project/shaka-player/pull/8453

**Comment by DevKeytech** [comment]
Hi,
in version 4.14.8 this issue is still present, will it be fixed only in 4.15?

**Comment by avelad** [comment]
I just released 4.14.9, can you review it again? Thanks!

**Comment by DevKeytech** [comment]
Nothing, still the transmission with chromecast does not happen. obviously always trying from 
https://shaka-player-demo.appspot.com/demo

Only the nightly version works.
