### ISSUE TITLE
Problems with fairplay polyfills/mediakeys since #8198?

### ISSUE THREAD

**Issue by fredrik-telia** [shaka-project/shaka-player#8590]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**
4.14.10

**What browser and OS are you using?**
Safari, macOS

**Please ask your question**
We're installing/uninstalling the Fairplay polyfills on each player start / teardown, did something happen in #8198 that causes any playbacks after the first one to fail, until the page is reloaded?

**Comment by fredrik-telia** [comment]
I did some initial troubleshooting in #8550 before doing a git bisect and arriving at the changes introduced in #8198

**Comment by avelad** [comment]
Interesting, because that PR addresses a user's use case where they mix different DRM providers using legacy Media Keys and Modern EME... Can you debug a little more when the error occurs?

**Comment by fredrik-telia** [comment]
the weirdest part, to me, was that I couldn't reproduce the issue when running shaka-player.compiled.debug.js 🤔

**Comment by fredrik-telia** [comment]
I think us uninstalling the polyfills is some tech debt remaining from when we used to have both shaka and hls.js playing fairplay content, we currently only use shaka, so I think we can disregard the part about uninstalling the polyfill.

We do however create a new player for each playback session, and install the PatchedMediaKeysApple polyfill each time, we don't reuse the same player instance

**Comment by fredrik-telia** [comment]
it is specifically this line:
```shaka.util.StreamUtils.clearDecodingConfigCache();```

If I remove that one, everything works as expected

**Comment by avelad** [comment]
@Robloche can you review it? It's related to https://github.com/shaka-project/shaka-player/issues/8190

**Comment by Robloche** [comment]
> [@Robloche](https://github.com/Robloche) can you review it? It's related to [#8190](https://github.com/shaka-project/shaka-player/issues/8190)

Will do today.

**Comment by fredrik-telia** [comment]
From what I can tell, the first time
`navigator.mediaCapabilities.decodingInfo(copy);`
returns something that makes sense, and content plays

the second time
`navigator.mediaCapabilities.decodingInfo(copy);`
returns `{powerEfficient: false, smooth: false, supported: false, supportedConfiguration: supportedConfiguration: type: "file", video: { bitrate: 100, contentType: "application/vnd.apple.mpegurl", framerate: 1, height: 64, width: 64}` and I get the error.

using the debug player, everything works, or using a modified version without `clearDecodingConfigCache()` everything also works

**Comment by Robloche** [comment]
> > [@Robloche](https://github.com/Robloche) can you review it? It's related to [#8190](https://github.com/shaka-project/shaka-player/issues/8190)
> 
> Will do today.

Just keep you updated: my build is broken and I won't be able to test today. Sorry.

**Comment by Robloche** [comment]
Against all odds, I fixed my build issue and was able to test Shaka v4.14.11.

It works as expected on my Mac, in Safari. I can play a stream, replay it, play another one, replay the first one again, etc.
Everything is still OK as far as I'm concerned.

**Comment by avelad** [comment]
@fredrik-telia @Robloche, Can you test if this patch would work in your cases? 

```diff
diff --git a/lib/util/stream_utils.js b/lib/util/stream_utils.js
index 856001bd3..e80ea0e32 100644
--- a/lib/util/stream_utils.js
+++ b/lib/util/stream_utils.js
@@ -569,9 +569,11 @@ shaka.util.StreamUtils = class {
    * If that query has been done before, instead return a cached result.
    * @param {!shaka.extern.Variant} variant
    * @param {!Array<!MediaDecodingConfiguration>} decodingConfigs
+   * @param {boolean} srcEquals
    * @private
    */
-  static async getDecodingInfosForVariant_(variant, decodingConfigs) {
+  static async getDecodingInfosForVariant_(
+      variant, decodingConfigs, srcEquals) {
     /**
      * @param {?MediaCapabilitiesDecodingInfo} a
      * @param {!MediaCapabilitiesDecodingInfo} b
@@ -621,7 +623,9 @@ shaka.util.StreamUtils = class {
                 acc = merge(acc, result);
               }
               if (acc) {
-                cache.set(cacheKey, acc);
+                if (!srcEquals) {
+                  cache.set(cacheKey, acc);
+                }
                 finalResult = merge(finalResult, acc);
               }
             }));
@@ -734,7 +738,7 @@ shaka.util.StreamUtils = class {
         for (const configs of decodingConfigs) {
           // eslint-disable-next-line no-await-in-loop
           await shaka.util.StreamUtils.getDecodingInfosForVariant_(
-              variant, configs);
+              variant, configs, srcEquals);
         }
         if (variant.decodingInfos.length) {
           keySystemSatisfied = true;
@@ -765,7 +769,7 @@ shaka.util.StreamUtils = class {
       for (const configs of decodingConfigs) {
         // eslint-disable-next-line no-await-in-loop
         await shaka.util.StreamUtils.getDecodingInfosForVariant_(
-            variant, configs);
+            variant, configs, srcEquals);
       }
     }
   }
```

**Comment by fredrik-telia** [comment]
Looks like I still get the same error, with the patch, unfortunately

**Comment by fredrik-telia** [comment]
disclaimer: I'm not an expert on the order of operations here

I think the problem is by the time execution reaches that part of the code, decodingInfo is already "wrong" (supported: false)

**Comment by avelad** [comment]
@tykus160 any theory?

**Comment by fredrik-telia** [comment]
Both fixes proposed in #8607 solve the issue for me
